{{- if and (.Values.sidekiq.autoscaling.enabled) (not .Values.sidekiq.singleMode.enabled) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mastodon.fullname" . }}-sidekiq-mailers
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mastodon.fullname" . }}-sidekiq-mailers
  minReplicas: {{ .Values.sidekiq.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sidekiq.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.sidekiq.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sidekiq.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.sidekiq.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.sidekiq.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
