# Adapted from https://github.com/mastodon/mastodon/blob/51a33ce77a32b85eaff37670c40a497aaef13e18/chart/templates/secrets.yaml
# Pulled on 2022-11-21
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mastodon.fullname" . }}
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
data:
  {{- if ( eq .Values.mastodon.storage.type "s3" ) }}
  {{- if not .Values.mastodon.storage.s3.existingSecret }}
  AWS_ACCESS_KEY_ID: "{{ .Values.mastodon.storage.s3.access_key | b64enc }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.mastodon.storage.s3.access_secret | b64enc }}"
  {{- end }}
  {{- end }}
  {{- if not .Values.mastodon.secrets.existingSecret }}
  {{- if not (empty .Values.mastodon.secrets.secret_key_base) }}
  SECRET_KEY_BASE: "{{ .Values.mastodon.secrets.secret_key_base | b64enc }}"
  {{- else }}
  SECRET_KEY_BASE: {{ required "secret_key_base is required" .Values.mastodon.secrets.secret_key_base }}
  {{- end }}
  {{- if not (empty .Values.mastodon.secrets.otp_secret) }}
  OTP_SECRET: "{{ .Values.mastodon.secrets.otp_secret | b64enc }}"
  {{- else }}
  OTP_SECRET: {{ required "otp_secret is required" .Values.mastodon.secrets.otp_secret }}
  {{- end }}
  {{- if not (empty .Values.mastodon.secrets.vapid.private_key) }}
  VAPID_PRIVATE_KEY: "{{ .Values.mastodon.secrets.vapid.private_key | b64enc }}"
  {{- else }}
  VAPID_PRIVATE_KEY: {{ required "vapid.private_key is required" .Values.mastodon.secrets.vapid.private_key }}
  {{- end }}
  {{- if not (empty .Values.mastodon.secrets.vapid.public_key) }}
  VAPID_PUBLIC_KEY: "{{ .Values.mastodon.secrets.vapid.public_key | b64enc }}"
  {{- else }}
  VAPID_PUBLIC_KEY: {{ required "vapid.public_key is required" .Values.mastodon.secrets.vapid.public_key }}
  {{- end }}
  {{- end }}
  {{- if not (empty .Values.mastodon.postgresql.auth.password )}}
  DB_PASS: {{ .Values.mastodon.postgresql.auth.password | b64enc }}
  PGPASSWORD: {{ .Values.mastodon.postgresql.auth.password | b64enc }}
  {{- else }}
  DB_PASS: {{ required "mastodon.postgresql.auth.password is required" .Values.mastodon.postgresql.auth.password }}
  {{- end }}
  {{- if not (empty .Values.mastodon.redis.auth.password )}}
  REDIS_PASS: {{ .Values.mastodon.redis.auth.password | b64enc }}
  {{- else }}
  REDIS_PASS: {{ required "mastodon.redis.auth.password is required" .Values.mastodon.redis.auth.password }}
  {{- end }}

