# Adapted from https://github.com/mastodon/mastodon/blob/75bbe3b1b80207d9cab1a73a9fc38324ee6340d5/chart/templates/cronjob-media-remove.yaml
# Pulled on 2022-11-23
{{ if .Values.mastodon.cron.removeMedia.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mastodon.fullname" . }}-media-remove
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.mastodon.cron.removeMedia.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ include "mastodon.fullname" . }}-media-remove
          {{- with .Values.jobAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: OnFailure
                {{- if (eq .Values.mastodon.storage.type "csi") }}
                # ensure we run on the same node as the other rails components; only
                # required when using PVCs that are ReadWriteOnce
                # FIXME: This might not work as intended on multi-AZ setups
                {{- if or (eq "ReadWriteOnce" .Values.mastodon.csi.assets.accessMode) (eq "ReadWriteOnce" .Values.mastodon.csi.system.accessMode) }}
                affinity:
                  podAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchExpressions:
                            - key: app.kubernetes.io/part-of
                              operator: In
                              values:
                                - rails
                        topologyKey: kubernetes.io/hostname
                {{- end }}
          volumes:
            - name: assets
              persistentVolumeClaim:
                claimName: {{ template "mastodon.fullname" . }}-assets
            - name: system
              persistentVolumeClaim:
                claimName: {{ template "mastodon.fullname" . }}-system
          {{- end }}
          containers:
            - name: {{ include "mastodon.fullname" . }}-media-remove
              image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - bin/tootctl
                - media
                - remove
              envFrom:
                - configMapRef:
                    name: {{ include "mastodon.fullname" . }}-env
                - secretRef:
                    name: {{ template "mastodon.secretName" . }}
              env:
                - name: "DB_PASS"
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "mastodon.postgresql.secretName" . }}
                      key: DB_PASS
                - name: "REDIS_PASSWORD"
                  valueFrom:
                    secretKeyRef:
                      name: {{ template "mastodon.redis.secretName" . }}
                      key: REDIS_PASS
              {{- if (not ( eq .Values.mastodon.storage.type "s3" ) ) }}
              volumeMounts:
                - name: assets
                  mountPath: /opt/mastodon/public/assets
                - name: system
                  mountPath: /opt/mastodon/public/system
              {{- end }}
{{- end }}
