apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-nginx
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: nginx
      protocol: TCP
      name: nginx
  selector:
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
